### ISSUE TITLE
Stock image backgrounds for download single sections

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#16]
I've got lots of credits [here](http://www.123rf.com/stock-photo/technology.html) and am thinking we might make our product pages much more professional by adding some photography instead of relying 100% on solid colors. Like what [Ross does](http://www.projectpanorama.com/#detailed-screenshots) all over the place.

Just an idea. But I do think we're relying too much on _just_ big blocks of solid colors. So maybe testimonials and/or requirements could get a picture background instead of a color. Pick a photo that would work and I'll download it.

**Comment by d4mation** [comment]
Right now I'm using CSS to color those based on `nth-of-type` which means if a section isn't present, it still colors them in-order. So if Testimonials weren't entered the next section would be green for example. This ensures we never have two solid colors right up against each other.

We could assign the blocks so that Green or Blue always has a certain background image from within `style.css`, but depending on the height of the section that gets the image applied to it that may look weird.

**Comment by brashrebel** [comment]
Hmmm...I think I'm a little less concerned about those situations where some sections don't exist. We don't have many products and we won't often be publishing any that don't have at least most of the sections. The only one I can think of that may occasionally be missing is the video which we might not have time to make for each plugin.

So in short, I am leaning towards making these sections always the same. We'll likely iterate a little more over time to make each section perfect (like we're doing in #19 for testimonials) so dynamically assigning a color will be less important.

I like this method you're using. It is super cool and efficient. I just think we're best suited by just making sure every section has content and making them look awesome.

**Comment by d4mation** [comment]
Good point. On our scale I guess the dynamic colors are less important.

I'm going to look into #12 some more and then I'll get back to this 👍

**Comment by d4mation** [comment]
Picked a couple. I think the first, more abstract one could work really well to just add some texture where it is otherwise flat. We could desaturate it and then make it any color we wanted. The second one could be used similar to how Ross has done on the Project Panorama site.

http://www.123rf.com/search.php?word=technology&start=400&searchopts=&itemsperpage=100&sti=llnfxm17do4feemxe3|&mediapopup=42719875

http://www.123rf.com/search.php?word=technology&start=100&searchopts=&itemsperpage=100&sti=llnfxm17do4feemxe3|&mediapopup=34573717

**Comment by brashrebel** [comment]
Just downloaded them and put them in the Stock Photos folder.

**Comment by d4mation** [comment]
I have it set so that Testimonials always has the Blue-overlayed background image and Requirements always has the Green-overlayed background image.

I'd like to do something more with features, but it is such a large section (And is the most likely to get extra large) that I'd be afraid to put an image there lest it get stretched too much.

**Comment by brashrebel** [comment]
Yeah, features can probably stay white. And I'm thinking the last item (purchase link) might look better with that background than the requirements. Requirements will typically be a small section and I'm still brainstorming for a more concise way to incorporate it. Maybe it should be last...it just isn't something that helps with selling the product so I think it should be further down. Or maybe much smaller up top listed around the pricing?

Also, the testimonials section is getting reinvented fairly soon too. I think its background looks great and probably will remain that way. Great stuff.

**Comment by d4mation** [comment]
I've give moving the requirements up top a shot. That could be a good spot for them.

I played with putting the Green-overlay background behind the Alternate Purchase Button at the bottom and it worked pretty well, but I was trying to separate things out more. If we moved the Requirements that will be less of a problem 👍

**Comment by d4mation** [comment]
I gave it a shot just below the content and I think it looks pretty good. I think that if we were to place it on the left by the pricing that it may make that section much larger.

Considering Gantt in particular requires a specific minimum version of PSP it may be good to include it near the content anyway.

![image](https://cloud.githubusercontent.com/assets/7770631/17260888/e805780c-55a0-11e6-8dcb-6914ac414f72.png)
