### ISSUE TITLE
New idea for styling testimonials

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#19]
Just had an idea for making the product testimonials look nicer.
![2016-07-28 16 49 19](https://cloud.githubusercontent.com/assets/4993131/17228996/8b20fcc8-54e3-11e6-801e-aeea9dfd5ac0.jpg)

They should still all have the same height within a row and determine width based on number of entries. The green background can remain for within the boxes...although I'm wondering whether just an outline might be better.

**Comment by d4mation** [comment]
Ooooh, I _really_ like this. 👍

**Comment by d4mation** [comment]
[I've got a really basic mockup going on JS Fiddle at the moment.](https://jsfiddle.net/d4mation/y43woyua/)

The Gear is an SVG as well as the Clipping Path around the Gravatar (Because of bad Browser Support in general for Clipping Paths via CSS). The content area is a `<div>`.

I don't know if we can make it just be simply an outlined edge since the gear and the content area are separate elements. If I could merge them into one SVG Path somehow that could be done, but I'm not sure if it could shrink/expand to the correct height as needed for _just_ the content area that way. Having them both be the same solid color hides the fact that they are different elements.

![image](https://cloud.githubusercontent.com/assets/7770631/17372623/a8d62a7a-5972-11e6-9501-0626337daa06.png)

**Comment by joelworsham** [comment]
I don't understand... why aren't we just copy/pasting @brashrebel's drawing onto the site as is? Beautiful.

**Comment by joelworsham** [comment]
![yus](https://cloud.githubusercontent.com/assets/4182573/17376043/bcaf0e68-5981-11e6-9251-836f94e4ee85.jpg)

**Comment by joelworsham** [comment]
I'm tired...

**Comment by d4mation** [comment]
Looks good to me! <sub>/s</sub>

**Comment by d4mation** [comment]
[This shows a full-screen version of what I've got going](https://jsfiddle.net/d4mation/y43woyua/embedded/result/)

I'm importing the CSS/JS from RBP into it so it should help see exactly what it will look like once it is hooked into the Theme.

**Comment by BigActual** [comment]
I like it. Would look nice for our staff page as well.

**Comment by brashrebel** [comment]
Can we go live with this?

**Comment by d4mation** [comment]
I don't know if I'd say it is in a ready state. I haven't been able to work on it for a while now :/

If you're happy with what's in that JSFiddle link above, I'd just have to get it hooked into the Template Files and include that small amount of CSS.

**Comment by brashrebel** [comment]
Ok, no worries. Thought it was done.

**Comment by joelworsham** [comment]
18 days ago?? Gosh time flies...

**Comment by d4mation** [comment]
We've got a cleaner Testimonials template as part of #39 that seems to work better 👍
