### ISSUE TITLE
Bring feature images closer to the center

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#24]
On download singles, the feature images align all the way to the right or left. For some features, as seen on the gantt addon, there's a big gap between the image and the text that relates to it. Looks...not ideal. Something like [this](https://woocommerce.com/storefront/) looks really nice. The obvious difference is the pics there are all the same size. We could either make new screenshots or play with the alignment so there's less of a noticeable gap.

Or maybe frame the images somehow? I'm not sure what to do here but it can be better.

**Comment by d4mation** [comment]
It is a bit tricky since we have those very narrow images. I've made the text a bit wider, the images a bit narrower, and centered all images to help make the extra spacing seem intentional. I think it helped a lot.

Before:
![image](https://cloud.githubusercontent.com/assets/7770631/17262202/0e7fe286-55a8-11e6-90f6-8e06f72e0e59.png)

After:
![image](https://cloud.githubusercontent.com/assets/7770631/17262167/d9b5e26c-55a7-11e6-9004-1e6a559aff3a.png)

**Comment by d4mation** [comment]
Covered in #39. Going to reupload screenshots over time to fit the space better.
