### ISSUE TITLE
Styling craziness on download grid in Safari

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#30]
Getting some weird stuff over in Safari:
<img width="373" alt="screenshot 2016-09-13 18 51 06" src="https://cloud.githubusercontent.com/assets/4993131/18494253/157a8000-79e3-11e6-8039-db05447ab71c.png">

**Comment by d4mation** [comment]
Looks like this is being caused by the Transitions. I disabled JavaScript in Safari and everything seems to work correctly. I've got code that is set to trigger a queue on-scroll to check if things (In this case, the Downloads) are in view and I think Safari doesn't like it very much.

I could try to refactor this, but possibly the quickest solution would be to make them all transition in at the same time. Safari doesn't seem to care about how I handled that on the Home Page.

**Comment by d4mation** [comment]
I opted for switching it to Transition them in at the same time and I actually think I like it better. It makes that page feel more immediate rather than having to wait for everything to appear (if you already know what you're looking for).
