### ISSUE TITLE
Downloads archive improvements

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#39]
I'm currently not a huge fan of our downloads archive page.

<img width="1126" alt="screenshot 2016-10-13 08 37 01" src="https://cloud.githubusercontent.com/assets/4993131/19349305/5860d712-9120-11e6-9696-e6b3e0ec9cb4.png">

I'd like to polish it up and make it look much nicer.

- [x] Ditch the Buy now on EDD site extra button for the external ones
- [ ] Make all logos _always_ exactly the same size
- [ ] Make all logos a consistent style (the white background ones don't match the colored ones and other styling differences just look blah)
- [ ] Make the grid always line up perfectly (look at the EDD addons page. It's beautiful. A perfect grid. We want that.)
- [x] Ditch the pricing
- [x] Add an excerpt

**Comment by joelworsham** [comment]
All of that sounds great. I will say that due to the nature of RBP, stylings won't match up. We can try to give the same overall feel to them, but colors will change, formatting will change etc. All of our plugins are for different things. Some are proprietary, some are extensions, some have legal liabilities on colors, etc. If they were all for the same product, I think that would be more attainable.

That said, I think there in fact *are* ways to make the stylings more cohesive for sure, and I'll work towards that.

**Comment by brashrebel** [comment]
Yeah, I agree. But I think we can increase standardization quite a bit. Like just make sure they all either do or don't have a background color. And making the actual logo part take up the same proportion of the image space. Stuff like that.

**Comment by joelworsham** [comment]
Here's a couple mocks I'm working on. Yes I borrowed some ideas from EDD ;) Tried to put our own flare on it though and plan to iterate it more.

Thoughts?

![product single](https://cloud.githubusercontent.com/assets/4182573/19356781/f0adb032-913c-11e6-86ad-8580a2d4798f.png)
![products](https://cloud.githubusercontent.com/assets/4182573/19356780/f0ad7bc6-913c-11e6-9701-18c08ac2a7c9.png)

**Comment by brashrebel** [comment]
Wow! @joelworsham these are really, really good! A little busy so I'll try and be concise.

The archive listing looks outstanding. I want it. Yes.

The single definitely looks more professional than what we have now. It's funny that you took cues from the EDD single template because it is actually being redesigned now. And the the even funnier part is, the early concept I saw was a full width design that was in concept much closer to our current live layout, although a lot cleaner.

So I'm a bit torn here. I absolutely LOVE your mockup, but I'm concerned that others have already found it lacking. I like what Foo Plugins does with their singles like [this one](http://fooplugins.com/plugins/foobox/). Maybe we should have further discussion about this. Like I said, your mockup looks gorgeous. But I'm seeing a move towards the full width, long form sales page with really creative visualizations of features, testimonials and sales videos. That's another note: We will be working towards making sure every product has a video so that should be included.

**Comment by joelworsham** [comment]
Thanks! All very good points and good to know. I'll experiment with pulling the layout apart a bit and putting it together in a less "sectionalized" approach.

**Comment by joelworsham** [comment]
I'm wondering if we can take cues from our own site, rbm.com. The home page is super full-width and I still really like it.

**Comment by brashrebel** [comment]
Still liking it a year after you made it is a tremendously positive sign.

**Comment by joelworsham** [comment]
What do you think about these?

![product single](https://cloud.githubusercontent.com/assets/4182573/19360393/52f5d152-914c-11e6-85d4-c30bb4aab6f4.png)
![products](https://cloud.githubusercontent.com/assets/4182573/19360394/52fb7bca-914c-11e6-8c0f-7336bfe8335d.png)

**Comment by joelworsham** [comment]
Updated the footer. I'm really happy with this.

![product single](https://cloud.githubusercontent.com/assets/4182573/19361338/519902da-9150-11e6-9e46-dd6b332fac6c.png)

**Comment by d4mation** [comment]
@joelworsham I'm a fan of that most recent Download Single mock!

**Comment by brashrebel** [comment]
😍  OMG this is gorgeous! Let's do it!!!!!!!!

I'm not sure about the pricing not being shown up top. Would that just be an anchor to the bottom section? Or reveal pricing? Also, our product descriptions are typically much longer than that teaser sentence at the top. Should we shorten them all or make that different?

**Comment by joelworsham** [comment]
Yeah I modeled after that one site you linked. The big button at the top links to the pricing at the bottom of the page.

I was wondering about the product teaser. Looking around, it's not super common to have really long, multi-paragraph text block describing it. Perhaps that should simply be incorporated into the feature sections? Otherwise I can find a place to throw it.

**Comment by brashrebel** [comment]
I'll plan on just condensing the product descriptions.

**Comment by d4mation** [comment]
Just created a new branch called `issue/39/downloads-archive-improvments` which has the new styling for the Downloads Archive. It looks pretty slick 👍 Too bad the `rbmin` staging site doesn't work at all... :/ We will probably just have to pull all this stuff Locally to get things how we all like it.

It doesn't pull in what looks like the Excerpt yet, but that's a simple addition.

**Comment by d4mation** [comment]
> We can try to give the same overall feel to them, but colors will change, formatting will change etc. All of our plugins are for different things. Some are proprietary, some are extensions, some have legal liabilities on colors, etc.

I was looking at starting up the Single Template and I noticed that the Featured Image for the Mock above appears to have a transparent background so that it merges into the blue banner. 

With style guides for the colors (Slack, for example, I remember having strict guidelines) having a transparent background shouldn't be a problem. But we probably don't want a transparent background on the Archive Page. Unless we just add a solid background color in the Archive via CSS so that each one is overlaid on the same color automagically?

**Comment by brashrebel** [comment]
Yeah, that sounds better. Let's use CSS for the background color and make all logos have a transparent background. Anyone disagree?

**Comment by d4mation** [comment]
As long as it is allowed across different style guides I'm fine with it. For the most part I think we'd just have to watch out for things like LearnDash blue against the blue header on the Download Single and whether or not different style guides permit using their logos on different background colors.

**Comment by brashrebel** [comment]
Just a tiny thought about the requirements box. Should we have each requirement always have " or higher" appended to it _or_ should we just label the box "Minimum Requirements"? Kind of leaning towards the latter.

Also, good points Eric. I think we can overcome those obstacles if/when they arise.

**Comment by d4mation** [comment]
I'm leaning toward the latter as well. It would be just as clear without having "or higher" repeated over and over again for each requirement 👍

**Comment by brashrebel** [comment]
Also, the email input field should probably be put in there right next to the subscribe button in the footer.

**Comment by joelworsham** [comment]
Why not just have the background in the image? I don't understand the point of adding CSS. There will always be exceptions to colors and it seems easier to simply add them to the image.

**Comment by joelworsham** [comment]
I had anticipated the link taking the user to a signup form generated from MailChimp. Seems easier that way to me. Any downsides I'm not aware of?

**Comment by d4mation** [comment]
I figured the logo in these two places would be identical, so that blue banner on the Single would be placed behind the logo.

Similarly on the Archive, where in the mock it is red. It could be any color, but having it be transparent with the background color set via CSS should prevent any weird conflicts where two separate images for Single/Archive would need to be used.

Am I looking at the Mocks incorrectly? That's how I interpreted them.

![image](https://cloud.githubusercontent.com/assets/7770631/19448560/5ee7a6f8-9470-11e6-8f0a-29c7050481b0.png)

![image](https://cloud.githubusercontent.com/assets/7770631/19448568/66d8d210-9470-11e6-994a-cfada2a19084.png)

**Comment by joelworsham** [comment]
My intent is that when you edit a single download you can set 2 colors, primary and secondary. In the Gradebook example, the primary color is that blue and the secondary is the lighter blue that you see in use as the box borders and also all of those alternate, light blue in the bottom, purchasing area. So every single page will have a different coloring options. I also envision these 2 colors having defaults that go with the RBM color theme, probably the blue, maybe green?

In this case, you would simply set that primary color identical to the color of the logo's background color in the image. In the archive screen, that red and white RBM logo is all just one image with the 2:1 proportions. The same image could show on both pages without hiccups.

This was simply how I envisioned it working in my mind. I'm, of course, open to options, I'm just failing to understand the need to style the background with CSS instead of the image itself.

**Comment by d4mation** [comment]
Ah, ok.

So you've got two color inputs: Primary and Secondary (Border color). The Primary color is used as the banner color and should match the background color of the logo.

I see what you're saying now. I was saying something pretty similar except I was thinking that on the Archive and Single the background color was/could be a different color. In that case, it would need to be done via CSS with a transparent image.

**Comment by joelworsham** [comment]
Hmmm I still don't *completely* follow :P Sorry, my brain is mushy today. Whatever works is fine in the end, I just don't see the need for CSS backgrounds with the scenario I had envisioned.

**Comment by brashrebel** [comment]
I may be missing some nuances to the discussion but it seems to be that making all the logos have a transparent background would allow us to use one image for both the archive and single while giving us maximum flexibility for display and reducing image sizes.

As for the opt in form in the footer, I think I'd rather have the field right there, just to the left of the button. No reason to send a user to a page off of our site if we don't have to.

**Comment by joelworsham** [comment]
It's 6 and 1 really for the logos I suppose. Whether a couple bits of png color information or another line of CSS, plus the image would work for both with colored background. Anyways, whichever way we go is fine by me, I was only trying to simplify.

If you'd like the field there, sure thing. They will be directed to another page either way won't they? The mailchipm message "confirm in your email blah blah"

**Comment by brashrebel** [comment]
We can show that message inline if we want. User does not have to go to another page and we definitely don't want them to.

**Comment by d4mation** [comment]
There is progress on this front. There's just a lot of wonky overrides I'm having to figure out for default EDD styling.

After I figure out how to fully handle the Testimonials, it should be mostly a matter of reorganizing the DOM to match the new structure.

The colors are brought in via colorpickers for the single to match the Logo background as discussed above. It does bring in images for the Features section, I just don't have any set in my local instance.

![image](https://cloud.githubusercontent.com/assets/7770631/19496676/8b5762e6-9556-11e6-8b3f-802940bf790e.png)

**Comment by brashrebel** [comment]
Looking great! This is going to be awesome!

**Comment by d4mation** [comment]
@joelworsham What's the plan for the `Get started with %s now!` button? Right now I have it linking to the Documentation page.

**Comment by brashrebel** [comment]
@d4mation that should link down to the pricing purchase button at the bottom of the page.

**Comment by joelworsham** [comment]
Looking great! Coming along.

@brashrebel Correct. That button scrolls down to the buy now area.

**Comment by d4mation** [comment]
Thinking Download Single should be 💯 tomorrow morning. All that's left is the Testimonials. Had to squash a lot of bugs with this new layout and the abominable sticky header/off-canvas combo. But as a result, now when you click Anchor Hash links the Sticky Header doesn't cover up the top of that section anymore!

I'm going to create a separate Issue for the Footer stuff right now as that's a bit more global and I think it should be part of a separate branch into Master.

![image](https://cloud.githubusercontent.com/assets/7770631/19536175/d6e22abc-9618-11e6-88cc-d0e69f09ddfa.png)

**Comment by joelworsham** [comment]
Nice! Being nitpicky, but could the pricing area be formatted identically? I had envisioned using a table with 3 cols, name, original price (if sale set), and final price. I had also envisioned using the font awsome icons for the radios. WOuld be `circle-o` and `check-circle-o`. Also have the selected row get the nice little background highlight? I think it looks nicer that way :)

Also, some sort of excerpt to go right under the title? And perhaps bold the title.

Okay that's it I swear!

This is looking great! 💯

**Comment by d4mation** [comment]
Will do! I've left the excerpt out at the moment as I know we will need to shorten down the content for this new template.

I'll do what I can with the Prices/Buy button. EDD's function for that is pretty limiting. I had to do most of what we've got right now via some creative CSS. The "Questions or concerns?" button is [done in a way that I would rather not have done](https://github.com/realbigplugins/theme2016/blob/29e2fa56234396add92608f6fe961466fcdf9d16/functions.php#L552) due to these limitations. :/ Those `circle-o` and `check-circle-o` bits should be possible though. The Sale price bit is automagic at the moment via EDD and I've set the styling for it accordingly 👍

**Comment by d4mation** [comment]
Archive looks a bit nasty as the Featured Images and Excerpts need to be properly set, but I think I addressed everything you were looking for with the Single, @joelworsham.

Going to tackle those Testimonials tomorrow.

![image](https://cloud.githubusercontent.com/assets/7770631/19543965/40044e64-9649-11e6-999b-c07edc1b25dc.png)

![image](https://cloud.githubusercontent.com/assets/7770631/19543974/5423c712-9649-11e6-9bce-147c6815c1ac.png)

**Comment by brashrebel** [comment]
😍 

Quick note since customers ask now and then: All price options are billed yearly with an automatic 20% discount.

**Comment by d4mation** [comment]
Added that note about the 20% discount as well as fixed up the Testimonials 👍 

![image](https://cloud.githubusercontent.com/assets/7770631/19561020/f21cbfd6-96a4-11e6-8af3-ea5660891932.png)

**Comment by joelworsham** [comment]
Nice!! Looks like you got the pricing looking great!!! <3

Could you possibly tighten the gap between the feature images and the text a bit? Make them feel almost "centered" within the layout, rather than budding up to the edges.

And then one more super nitpicky thing, the boxes at the bottom, could you remove the bullets? I was thinking also style the "Requirements" box with the left/right justification, but I'm open to not doing that, as it may not look like it matches the other 2 boxes.

**Comment by d4mation** [comment]
Something like this? I had the images centered in their own columns before as a result of #24.

If I just align the Images then things look even more off-centered within the page. :/ Most of our screenshots across the site for the Features section are all portrait which makes them look very small within the space. 

![image](https://cloud.githubusercontent.com/assets/7770631/19562204/6f90fadc-96a9-11e6-9169-a7775b020c20.png)

**Comment by d4mation** [comment]
Attached the wrong screenshot before. I've included how it looks like in both instances.

**Comment by brashrebel** [comment]
I'm torn. In these images, I do kinda think the alternating text alignment looks better.

**Comment by joelworsham** [comment]
Personally I like that more, but we can take this one step further by creating some internal rules about screenshots. I think they can be bigger and wider. The sizing/proportion from my initial mock is what would look best. 

Let's make it a priority to get some new screenshots to fit this layout.

Let's require these feature images to be:

1000x750

@brashrebel what do yo mean? Aren't they still alternating in alignment?

**Comment by joelworsham** [comment]
@d4mation For our own sake of remembering, can you add a note to adding the feature images for the required sizing?  I know I'll forget :P

**Comment by d4mation** [comment]
Will do 👍 

So we've decided on the second screenshot that I attached?

**Comment by joelworsham** [comment]
I would not right-align the text. I would keep it left aligned, like the mock. It's not as nice to read right aligned paragraphs

**Comment by joelworsham** [comment]
So even though the image jumps side to side, the text remains left aligned.

Original for reference:

<img width="490" alt="screen shot 2016-10-20 at 10 05 48 am" src="https://cloud.githubusercontent.com/assets/4182573/19563114/d400a08c-96ac-11e6-9e79-bbce7ee1057b.png">

**Comment by d4mation** [comment]
Gotcha, just making sure. It's a simple change to the code either way.

**Comment by brashrebel** [comment]
I'm hoping we can deploy this and _then_ get on the featured image and screenshot replacements. That possible? Would be a bummer to go through all of the images first. That could take a couple days. Anyway, love where this is going and am fine with those decisions.

**Comment by d4mation** [comment]
It would be possible, but it may not look very pretty 😛 The top banner on the Single defaults to the same Blues on the Archive if none are defined. The idea is to match it to the background color of the Featured Image.

We'd also want to rewrite the Content for each one (probably *before* we deploy) because within the Banner on the Single it outputs everything within the Content. Some of them are a bit lengthy and may not look so nice.

**Comment by joelworsham** [comment]
I can lend a hand to this today, re-writing + screenshots. At the very least we can deploy with some of the "smaller" plugins not having any features yet?

**Comment by d4mation** [comment]
> And then one more super nitpicky thing, the boxes at the bottom, could you remove the bullets? I was thinking also style the "Requirements" box with the left/right justification, but I'm open to not doing that, as it may not look like it matches the other 2 boxes.

@joelworsham I looked at this again and for the Requirements Box it spits out whatever is placed within the Repeater. So unless we restructured that significantly (Key/Value Pairs) or used some nasty Regex or something we can't really split them for right justified values.

It may be best for the time being to just remove the bullet points, especially since it wouldn't match the other two very well since they are mostly links.

**Comment by joelworsham** [comment]
Ah I see, so it's one line of text. No problem! It still looks good.

**Comment by d4mation** [comment]
Updated screenshot. Everything you see is in the remote branch right now.

![image](https://cloud.githubusercontent.com/assets/7770631/19565861/606b4082-96b6-11e6-8090-4ea1847deb56.png)

**Comment by joelworsham** [comment]
This. Looks. Phenomenal. Excellent work @d4mation !

**Comment by brashrebel** [comment]
I'm so happy. When can we make it so? What help is needed?

**Comment by d4mation** [comment]
I think rewriting the content for each Download down to a sentence or two (like in the screenshot/mock) is the highest priority. Otherwise this design won't look nice for other Downloads.

Featured Images and Images for the Features Section being redone is important but could wait if needed.

**Comment by brashrebel** [comment]
I'll try and tackle that for every download today.

**Comment by joelworsham** [comment]
I'll get some screenshots

**Comment by d4mation** [comment]
I just realized that the Single Template doesn't load a video that's attached as Post Meta, like you can see [here](https://realbigplugins.com/plugins/render-easy-digital-downloads/).

Should we just add that above the pricing section using the similar styling to the Features section?

**Comment by brashrebel** [comment]
Yeah, I forgot about that too. We will be working towards all plugins having a video so its placement is important. I guess just put it in there some place. Above or below testimonials.

**Comment by d4mation** [comment]
Added back in. 👍 

I'd say this code is ready to deploy whenever unless we want to wait for new Featured Images/Features Section Screenshots.

![image](https://cloud.githubusercontent.com/assets/7770631/19601616/09bbd040-9778-11e6-940d-8145797a5990.png)

**Comment by brashrebel** [comment]
I say let's deploy!!!! 🚀  :shipit:

**Comment by d4mation** [comment]
Deployed! 🚀 

I've noticed a couple small bugs so far on Live (For external downloads), but they are visual and shouldn't be too difficult to fix. 

Although, at least on EDD Message, I noticed there is not a Current Version defined. The Template pulls that in for the Plugin Details section so we should probably add that even though it isn't hosted on our site.

**Comment by joelworsham** [comment]
It should probably jump to 2 columns on medium screens:

https://i.imgur.com/jaIYI3w.png

**Comment by joelworsham** [comment]
Wow this is nice

**Comment by joelworsham** [comment]
Also, nitpicky I know :P, could the feature headers be bold? Like:

https://i.imgur.com/fF8lJew.png

**Comment by joelworsham** [comment]
I know that my mock had "Our Products" as the archive header, but I realize now that doesn't really line up. Should probably be "Our Plugins": https://i.imgur.com/LniOz8K.png

**Comment by joelworsham** [comment]
Man, look at me not contextualizing things... let me open up some issues :P

**Comment by brashrebel** [comment]
Ha. Yeah, this is a super long issue now. I think since it is deployed we should close it.
