### ISSUE TITLE
Logout takes user to RBM instead of RBP Loign screen

### ISSUE THREAD

**Issue by BigActual** [realbigplugins/theme2016#60]
![image](https://cloud.githubusercontent.com/assets/8271108/25483787/4bbdd2ae-2b25-11e7-83ca-03c6ae257dfe.png)

When a user logs out, I'd prefer that they end that process on an RBP login screen.

**Comment by joelworsham** [comment]
yup that's bad

**Comment by joelworsham** [comment]
I believe it's a multisite issue. Logging out takes you back to the main network site temporarily, but then redirects back to the site with the matching "blog_id" in the URL. The issue is that that temporary redirect is trying to still use https, and RBM.com does not have it. So the browser halts you and you see this.

Solutions:

1. Just get SSL on RBM. Probably should anyways
2. Figure out way to manually configure that redirect as non-SSL

I vote 1. What say you?

**Comment by BigActual** [comment]
Go with 1

**Comment by d4mation** [comment]
@joelworsham took care of this back on June 13th :tada:
