### ISSUE TITLE
Create additional Role, Guest Contributor

### ISSUE THREAD

**Issue by BigActual** [realbigplugins/theme2016#64]
The current Contributor role provides a touch to much access. Please create a Guest Contributor role that does not allow access to Holler Box or comments on posts the contributor did not create.
![image](https://user-images.githubusercontent.com/8271108/33334795-1db85e52-d439-11e7-9c82-70f162977be5.png)

**Comment by d4mation** [comment]
Restricting Comments that way will not be possible without some heavy modifications. This is because the way WordPress Core handles Comments in the Dashboard in general is incredibly poor.

It checks if the user has the `edit_posts` capability and if they do, lets them run wild with Comments. Pretty much the only way I'd be able to restrict comments like you're saying would be to fully replace their Comments Page in the WP Admin with something like we did for Adrian with the Comment Assignment. I'd have to create a custom Comments Page for this Role which only queried for Comments on Posts that they created. Not impossible, but a lot of work. 

If they were to get Comments on their Posts, wouldn't they also get an email? I figure Guest Contributions aren't going to be horribly regular. Would they instead be able to reply via the Frontend when they receive an email notification about it?

**Comment by BigActual** [comment]
Per your idea, just restrict access to the back end for comments altogether.
