### ISSUE TITLE
Make download category archives look like the main downloads page

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#66]
Example: https://realbigplugins.com/plugins/category/bundle/

**Comment by joelworsham** [comment]
gross

**Comment by d4mation** [comment]
I opted to surround the Category/Tag name with "All <term name> Plugins" to help contextualize it a little. We may want to change the Term Name for "Bundle" though to be "Bundled" or we could otherwise change the wording in the Template File. 

![image](https://user-images.githubusercontent.com/7770631/33949251-13e879c4-dff7-11e7-85c8-2c5ad79a78cd.png)
